server:
  port: 8081

spring:
  application:
    name: order-service

  http:
    clients:
      connect-timeout: 2s
      read-timeout: 2s

  datasource:
    url: jdbc:postgresql://localhost:5432/orderdb
    username: postgres
    password: postgres

  jpa:
    open-in-view: false
    show-sql: true

    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true

  kafka:
    bootstrap-servers: localhost:9092

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JacksonJsonSerializer

      properties:
        spring.json.add.type.headers: false

app:
  kafka:
    topics:
      order-created: order.created